GET http://localhost:8080
###
GET http://localhost:8080/info
###
GET http://localhost:8080/recipe/1
###
POST http://localhost:8080/recipe
Content-Type: application/json

{
    "name": "Сырники из творога",
    "cookingTimeInMinutes": 40,
    "ingredients": [
      {
        "name": "Творог",
        "quantity": 350,
        "measureUnit": "г"
      },
      {
        "name": "Куриное яйцо",
        "quantity": 2,
        "measureUnit": "штуки"
      },
      {
        "name": "Пшеничная мука",
        "quantity": 6,
        "measureUnit": "столовых ложек"
      },
      {
        "name": "Сахар",
        "quantity": 2,
        "measureUnit": "столовые ложки"
      }
    ],
    "cookingSteps": [
      "Смешайте весь творог с яйцами, сахаром и тщательно всё перемешайте",
      "Всыпьте в творог муку и тщательно перемешайте",
      "Поставьте сковороду на средний огонь и налейте в нее подсолнечное масло",
      "Слепите несколько небольших шариков из получившейся творожной массы и положите их на тарелку. Затем по очереди обкатывайте творожные шарики в муке и выкладывайте на сковороду",
      "Обжаривайте сырники 1–2 минуты до появления золотистой корочки. Затем переверните их на другую сторону и также обжарьте до золотистого состояния",
      "Повторяйте, пока творог не закончится"
    ]
  }
###
POST http://localhost:8080/recipe
Content-Type: application/json

{
  "name": "Салат из красной фасоли с творожным сыром, красным луком и сезонным салатом",
  "cookingTimeInMinutes": 7,
  "ingredients": [
    {
      "name": "Специи",
      "quantity": 0,
      "measureUnit": "по вкусу"
    },
    {
      "name": "Консервированная фасоль",
      "quantity": 400,
      "measureUnit": "г"
    },
    {
      "name": "Лимон",
      "quantity": 1,
      "measureUnit": "штука"
    },
    {
      "name": "Чеснок",
      "quantity": 2,
      "measureUnit": "зубчика"
    },
    {
      "name": "Оливковое масло",
      "quantity": 50,
      "measureUnit": "мл"
    },
    {
      "name": "Рукола",
      "quantity": 100,
      "measureUnit": "г"
    },
    {
      "name": "Творожный сыр",
      "quantity": 200,
      "measureUnit": "г"
    },
    {
      "name": "Красный лук",
      "quantity": 50,
      "measureUnit": "г"
    }
  ],
  "cookingSteps": [
    "Открыть две банки красной фасоли в собственном соку, слить сок и промыть фасоль холодной водой",
    "Готовую фасоль смешать с мелко нарубленным красным луком, зеленью, давленым чесноком, оливковым маслом, лимонным соком и творожным сыром",
    "Посолить, поперчить, дать продуктам две минуты притереться друг к другу и подавать к столу"
  ]
}
###
POST http://localhost:8080/recipe
Content-Type: application/json

{
  "name": "Чечевичный суп с мятой",
  "cookingTimeInMinutes": 30,
  "ingredients": [
    {
      "name": "Красная чечевица",
      "quantity": 150,
      "measureUnit": "г"
    },
    {
      "name": "Репчатый лук",
      "quantity": 1,
      "measureUnit": "головка"
    },
    {
      "name": "Морковь",
      "quantity": 1,
      "measureUnit": "штука"
    },
    {
      "name": "Подсолнечное масло",
      "quantity": 30,
      "measureUnit": "мл"
    },
    {
      "name": "Лимон",
      "quantity": 0.5,
      "measureUnit": "штуки"
    },
    {
      "name": "Сливочное масло",
      "quantity": 15,
      "measureUnit": "г"
    },
    {
      "name": "Пшеничная мука",
      "quantity": 30,
      "measureUnit": "г"
    },
    {
      "name": "Сливки 33%",
      "quantity": 50,
      "measureUnit": "мл"
    },
    {
      "name": "Специи",
      "quantity": 0,
      "measureUnit": "по вкусу"
    },
    {
      "name": "Мята",
      "quantity": 0,
      "measureUnit": "по вкусу"
    }
  ],
  "cookingSteps": [
    "В небольшую кастрюлю налить литр воды и засыпать промытую чечевицу. Поставить кастрюлю на средний огонь",
    "Натереть небольшую морковь на крупной терке, мелко нарезать лук. Как только чечевица начнет кипеть, надо убавить огонь, а затем долить еще 200 мл воды или бульона. Варить еще десять минут",
    "Разогреть широкую плоскую сковороду, добавить туда подсолнечное и сливочное масло. Обжарить лук и морковь",
    "Добавить обжаренные овощи в кастрюлю, влить сливки. Взбить суп ручным блендером, чтобы он превратился в густое пюре. Суп можно подавать к столу"
  ]
}
###
POST http://localhost:8080/recipe
Content-Type: application/json

{
  "name": "Салат с креветками и кунжутом",
  "cookingTimeInMinutes": 20,
  "ingredients": [
    {
      "name": "Помидоры",
      "quantity": 3,
      "measureUnit": "штуки"
    },
    {
      "name": "Королевские креветки",
      "quantity": 300,
      "measureUnit": "г"
    },
    {
      "name": "Зеленый салат",
      "quantity": 1,
      "measureUnit": "пучок"
    },
    {
      "name": "Огурцы",
      "quantity": 2,
      "measureUnit": "штуки"
    },
    {
      "name": "Кунжутные семечки",
      "quantity": 3,
      "measureUnit": "столовые ложки"
    },
    {
      "name": "Специи",
      "quantity": 0,
      "measureUnit": "по вкусу"
    },
    {
      "name": "Майонез",
      "quantity": 0,
      "measureUnit": "по вкусу"
    }
  ],
  "cookingSteps": [
    "Порезать овощи крупно, салат порвать на куски",
    "Довести до кипения сильно соленую воду и добавить креветки. После кипения варить 5 минут",
    "Очистить креветки от панциря",
    "Смешать овощи и креветки",
    "Посыпать кунжутными семечками и заправить майонезом"
  ]
}
###
      POST http://localhost:8080/recipe
Content-Type: application/json

{
  "name": "Творожные пончики в сахарной пудре",
  "cookingTimeInMinutes": 40,
  "ingredients": [
    {
      "name": "Творог",
      "quantity": 250,
      "measureUnit": "г"
    },
    {
      "name": "Куриное яйцо",
      "quantity": 3,
      "measureUnit": "штуки"
    },
    {
      "name": "Пшеничная мука",
      "quantity": 8,
      "measureUnit": "столовых ложек"
    },
    {
      "name": "Сахар и соль",
      "quantity": 0,
      "measureUnit": "по вкусу"
    },
    {
      "name": "Сода",
      "quantity": 0.5,
      "measureUnit": "чайные ложки"
    },
    {
      "name": "Оливковое масло",
      "quantity": 0,
      "measureUnit": "по вкусу"
    },
    {
      "name": "Сахарная пудра с ванилью",
      "quantity": 0,
      "measureUnit": "по вкусу"
    }
  ],
  "cookingSteps": [
    "В миске смешать творог, яйца, муку, сахар, соду и соль до однородной консистенции",
    "В небольшом сотейнике оливковое масло хорошо разогреть",
    "При помощи чайной ложки или руками скатать из теста шарики, каждый размером чуть меньше грецкого ореха",
    "Бросить пончики в кипящее масло и жарить на небольшом огне, постоянно переворачивая шумовкой",
    "Готовые пончики выложить на бумажное полотенце и оставить на одну-две минуты — чтобы оно впитало лишнее масло. Подавать пончики горячими, выложив на блюдо и посыпав сахарной пудрой, смешанной с ванилином"
  ]
}
###
GET http://localhost:8080/recipe/3
###
GET http://localhost:8080/recipe
###
DELETE http://localhost:8080/recipe/3
###
GET http://localhost:8080/recipe/1
###
DELETE http://localhost:8080/recipe
###
GET http://localhost:8080/recipe/1
###
POST http://localhost:8080/ingredient
Content-Type: application/json

    {
      "name": "Творог",
      "quantity": 250,
      "measureUnit": "г"
    }
###
POST http://localhost:8080/ingredient
Content-Type: application/json

    {
      "name": "Куриное яйцо",
      "quantity": 3,
      "measureUnit": "штуки"
    }
###
POST http://localhost:8080/ingredient
Content-Type: application/json

    {
      "name": "Пшеничная мука",
      "quantity": 8,
      "measureUnit": "столовых ложек"
    }
###
POST http://localhost:8080/ingredient
Content-Type: application/json

    {
      "name": "Сахар и соль",
      "quantity": 0,
      "measureUnit": "по вкусу"
    }
###
POST http://localhost:8080/ingredient
Content-Type: application/json

    {
      "name": "Сода",
      "quantity": 0.5,
      "measureUnit": "чайные ложки"
    }
###
POST http://localhost:8080/ingredient
Content-Type: application/json

    {
      "name": "Оливковое масло",
      "quantity": 0,
      "measureUnit": "по вкусу"
    }
###
POST http://localhost:8080/ingredient
Content-Type: application/json

    {
      "name": "Сахарная пудра с ванилью",
      "quantity": 0,
      "measureUnit": "по вкусу"
    }

###
GET http://localhost:8080/ingredient/2
###
GET http://localhost:8080/ingredient
###
DELETE http://localhost:8080/ingredient/2
###
GET http://localhost:8080/ingredient/5